print("Welcome to you the Bridge of Death")
print("What is your name?")
name = input()
print("What is you quest?")
quest = input()
print("What is your favourite colour?")
colour = input()
print(name)
print(quest)
print(colour)
print("\nHello," name, "goode luck with your", quest, "quest!")
print("Perhaps wearing", colour, "socks would help :)"\n)
print()
